### ISSUE TITLE
since_months darf nicht 0 sein

### ISSUE THREAD

**Issue by thomst** [systopia/civicrm-fake-data#2]
Wenn in Zeile 152 SecureRandom.random_number für since_months eine 0 generiert, dann gibt  SecureRandom.random_number(since_months) in Zeile 158 einen float zwischen 0 und 1 zurück.
Damit kommt es zu folgendem Fehler:

generate_contacts.rb:170:in `each': can't iterate from Float (TypeError)
	from generate_contacts.rb:170:in `block in <main>'
	from generate_contacts.rb:150:in `each'
	from generate_contacts.rb:150:in `<main>'

Zeile 152 muss folgendermaßen lauten:
since_months = SecureRandom.random_number($contribution_timespan) + 1

**Comment by tpokorra** [comment]
das wurde bereits umgesetzt: https://github.com/bjendres/civicrm-fake-data/blob/master/generate_contacts.rb#L176
